// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AlgoliaSearchBox: typeof import('./.vitepress/theme/components/algolia-search-box.vue')['default']
    AppLogo: typeof import('./.vitepress/theme/components/logos/app-logo.vue')['default']
    'Bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Carbon:arrowLeft': typeof import('~icons/carbon/arrow-left')['default']
    'Carbon:pen': typeof import('~icons/carbon/pen')['default']
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    DropdownLink: typeof import('./.vitepress/theme/components/dropdown-link.vue')['default']
    DropdownMenu: typeof import('./.vitepress/theme/components/dropdown-menu.vue')['default']
    EditLink: typeof import('./.vitepress/theme/components/edit-link.vue')['default']
    HeroiconsOutlineMenuAlt2: typeof import('~icons/heroicons-outline/menu-alt2')['default']
    Home: typeof import('./.vitepress/theme/components/layout/home.vue')['default']
    IconButton: typeof import('./.vitepress/theme/components/icon-button.vue')['default']
    IonIosSunny: typeof import('~icons/ion/ios-sunny')['default']
    LastUpdated: typeof import('./.vitepress/theme/components/last-updated.vue')['default']
    Layout: typeof import('./.vitepress/theme/components/layout/layout.vue')['default']
    LayoutFooter: typeof import('./.vitepress/theme/components/layout/layout-footer.vue')['default']
    LayoutHeader: typeof import('./.vitepress/theme/components/layout/layout-header.vue')['default']
    'Mdi:cogOutline': typeof import('~icons/mdi/cog-outline')['default']
    NavLink: typeof import('./.vitepress/theme/components/nav-link.vue')['default']
    NextAndPreviousLinks: typeof import('./.vitepress/theme/components/next-and-previous-links.vue')['default']
    Page: typeof import('./.vitepress/theme/components/layout/page.vue')['default']
    Sidebar: typeof import('./.vitepress/theme/components/layout/sidebar.vue')['default']
    SidebarBackground: typeof import('./.vitepress/theme/components/layout/sidebar-background.vue')['default']
    SidebarHeader: typeof import('./.vitepress/theme/components/layout/sidebar-header.vue')['default']
    SidebarLink: typeof import('./.vitepress/theme/components/layout/sidebar-link.vue')['default']
    SidebarLinkItem: typeof import('./.vitepress/theme/components/sidebar-link-item.vue')['default']
    SidebarNav: typeof import('./.vitepress/theme/components/layout/sidebar-nav.vue')['default']
    SidebarRight: typeof import('./.vitepress/theme/components/layout/sidebar-right.vue')['default']
    TableOfContents: typeof import('./.vitepress/theme/components/table-of-contents.vue')['default']
    ToggleDark: typeof import('./.vitepress/theme/components/toggle-dark.vue')['default']
    ToggleSidebar: typeof import('./.vitepress/theme/components/toggle-sidebar.vue')['default']
    TreeLink: typeof import('./.vitepress/theme/components/tree-link.vue')['default']
    TreeMenu: typeof import('./.vitepress/theme/components/tree-menu.vue')['default']
    UilAngleDown: typeof import('~icons/uil/angle-down')['default']
    UilAngleRight: typeof import('~icons/uil/angle-right')['default']
  }
}

export { }
